image_width: 640
image_height: 480
camera_name: C93-Orange
camera_matrix:
  rows: 3
  cols: 3
  data: [498.64644,   0.     , 313.76504,
           0.     , 500.76878, 248.5328 ,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.073022, -0.192040, 0.001795, -0.005144, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [496.87745,   0.     , 309.89989,   0.     ,
           0.     , 504.54111, 249.25393,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
