/**:
  ros__parameters:
    # =============================================================================
    # 토픽 설정 (launch 파일에서 오버라이드 가능)
    # =============================================================================
    
    # 입력 포인트클라우드 토픽
    input_pointcloud_topic: "/pointcloud/noise_removed"
    
    # 출력 토픽들
    output_pointcloud_topic: "/pointcloud/ground_removed"          # 비지면 포인트 (장애물)
    output_ground_pointcloud_topic: "/pointcloud/ground_only"      # 지면 포인트만
    
    # 처리 시간 정보 토픽
    processing_time_topic: "/debug/processing_time_ms"
    processing_time_detail_topic: "/debug/processing_time_detail_ms"

    common_ground_filter:
      plugin: "autoware::ground_segmentation::ScanGroundFilterComponent"
      parameters:
        # =============================================================================
        # 모드 선택 파라미터
        # =============================================================================
        
        # 그리드 모드 vs 스캔 모드 선택
        # false: 스캔 모드 (ray별 순차적 처리, 빠름, 실외)
        # true: 그리드 모드 (격자 기반, 정확함, 실내/복잡한 환경)
        elevation_grid_mode: false
        
        # 가상 지면점 사용 여부 (차량 휠베이스 위치에서 지면 추정 시작)
        # true: 더 안정적인 지면 시작점, 차량 근처 정확도 향상
        # false: 원점(0,0,0)에서 시작, 더 단순한 처리
        use_virtual_ground_point: true

        # =============================================================================
        # 경사 임계값 파라미터 (가장 중요한 튜닝 포인트)
        # =============================================================================
        
        # 전역 경사 최대 각도 [degree]
        # 값 증가 → 더 가파른 경사까지 지면으로 인식 (언덕길, 경사로)
        # 값 감소 → 더 평평한 면만 지면으로 인식 (평지, 실내)
        # 권장: 평지 3-8도, 언덕길 10-15도
        global_slope_max_angle_deg: 10.0
        
        # 로컬(지역적) 경사 최대 각도 [degree]
        # 인접 포인트간 경사 허용값, global보다 작게 설정
        # 값 증가 → 작은 요철/노이즈 허용 증가
        # 값 감소 → 더 매끄러운 지면만 인식
        local_slope_max_angle_deg: 2.0

        # =============================================================================
        # 포인트간 연결성 파라미터
        # =============================================================================
        
        # 포인트간 거리 허용 오차 [m]
        # 값 증가 → 멀리 떨어진 포인트도 같은 지면으로 연결 (스파스한 데이터)
        # 값 감소 → 더 조밀한 연결만 허용 (덴스한 데이터)
        # 권장: VLP-16/32는 3-4m, 고해상도 라이다는 1-2m
        split_points_distance_tolerance: 2.75
        
        # 높이 차이 허용값 [m]
        # 포인트간 z축 차이 허용 범위
        # 값 증가 → 높이 변화 큰 지형 허용 (비포장도로, 언덕)
        # 값 감소 → 평평한 지면만 허용 (실내, 포장도로)
        split_height_distance: 0.075
        
        # 지면 모델 대비 높이 임계값 [m]
        # 추정된 지면에서 이 값 이상 높으면 장애물로 분류
        # 값 증가 → 더 관대한 장애물 검출 (작은 물체 무시)
        # 값 감소 → 더 민감한 장애물 검출 (작은 물체도 검출)
        non_ground_height_threshold: 0.05

        # =============================================================================
        # 스캔 분해능 파라미터
        # =============================================================================
        
        # 방위각 분할 각도 [degree]
        # 값 감소 → 더 세밀한 ray 분할, 정확도 향상, 처리 시간 증가
        # 값 증가 → 더 거친 ray 분할, 빠른 처리, 정확도 감소
        # 권장: 일반적으로 0.5-1.0도
        radial_divider_angle_deg: 0.2

        # =============================================================================
        # 그리드 모드 전용 파라미터 (elevation_grid_mode: true일 때만 유효)
        # =============================================================================
        
        # 그리드 셀 크기 [m]
        # 값 감소 → 더 세밀한 격자, 높은 정확도, 많은 메모리/연산
        # 값 증가 → 더 큰 격자, 빠른 처리, 낮은 정확도
        grid_size_m: 0.15
        
        # 그리드 모드 전환 거리 [m]
        # 이 거리 이후부터 그리드 기반 처리 적용
        # 값 감소 → 가까운 거리부터 그리드 모드
        # 값 증가 → 먼 거리부터 그리드 모드
        grid_mode_switch_radius: 20.0
        
        # 지면 그리드 버퍼 크기
        # 지면 연결성 판단 시 참고할 이전 셀 개수
        # 값 증가 → 더 안정적인 지면 추정, 느린 처리
        # 값 감소 → 빠른 처리, 불안정할 수 있음
        gnd_grid_buffer_size: 4

        # =============================================================================
        # 검출 범위 제한 파라미터
        # =============================================================================
        
        # Z축 최대 검출 범위 [m]
        # 이 높이 이상의 포인트는 무시
        # 값 증가 → 더 높은 물체까지 검출 (크레인, 나무 등)
        # 값 감소 → 낮은 물체만 검출 (차량, 사람 등)
        detection_range_z_max: 2.5
        
        # 저우선순위 영역 X 좌표 [m]
        # 이 X값 이하 영역은 낮은 우선순위로 처리
        # 음수로 설정하여 차량 뒤쪽 영역을 의미
        low_priority_region_x: -5.0
        
        # 포인트클라우드 중심 이동값 [m]
        # 센서 장착 위치 오프셋 보정
        # 차량 중심에서 라이다 위치까지의 X축 거리
        center_pcl_shift: 1.0

        # =============================================================================
        # 고급 필터링 옵션
        # =============================================================================
        
        # 지면 클러스터 재검사 사용 여부
        # true: 지면으로 분류된 포인트를 다시 검사하여 정확도 향상
        # false: 빠른 처리, 정확도 약간 감소
        # 권장: 정확도가 중요한 경우 true
        use_recheck_ground_cluster: false
        
        # 최저점 기준 사용 여부
        # true: 클러스터의 최저점을 기준으로 지면 높이 결정
        # false: 평균 높이를 기준으로 결정
        # 권장: 노이즈가 많은 환경에서는 false
        use_lowest_point: false

        # =============================================================================
        # 디버그 및 성능 모니터링
        # =============================================================================
        
        # 상세 처리 시간 발행 여부
        # true: 각 단계별 처리 시간을 /debug/processing_time_detail_ms 토픽으로 발행
        # false: 기본적인 시간 정보만 발행
        publish_processing_time_detail: false

# =============================================================================
# 튜닝 가이드 요약
# =============================================================================
#
# 1. 실내 환경:
#    - elevation_grid_mode: true
#    - global_slope_max_angle_deg: 3.0
#    - non_ground_height_threshold: 0.1
#    - radial_divider_angle_deg: 0.5
#
# 2. 실외 평지:
#    - elevation_grid_mode: false
#    - global_slope_max_angle_deg: 8.0
#    - split_points_distance_tolerance: 4.0
#
# 3. 언덕/경사 지형:
#    - global_slope_max_angle_deg: 15.0
#    - local_slope_max_angle_deg: 10.0
#    - split_height_distance: 0.3
#
# 4. 고속 처리 필요시:
#    - radial_divider_angle_deg: 1.0
#    - use_recheck_ground_cluster: false
#    - grid_size_m: 2.0
#
# 5. 고정밀 처리 필요시:
#    - radial_divider_angle_deg: 0.3
#    - grid_size_m: 0.5
#    - use_recheck_ground_cluster: true
#
# 6. 스파스한 포인트클라우드:
#    - split_points_distance_tolerance: 5.0
#    - gnd_grid_buffer_size: 4
#
# 7. 덴스한 포인트클라우드:
#    - split_points_distance_tolerance: 2.0
#    - radial_divider_angle_deg: 0.5
