/**:
  ros__parameters:
    # =============================================================================
    # 좌표계 및 기본 설정
    # =============================================================================
    
    # 기준 좌표계 (일반적으로 base_link 또는 velodyne)
    # base_link: 차량 중심 좌표계
    # velodyne: 라이다 센서 좌표계
    base_frame: "base_link"
    
    # 지면 수직 방향 축 설정
    # "z": 일반적인 설정 (Z축이 위쪽)
    # "y": 카메라 좌표계 (Y축이 위쪽)
    # "x": 특수한 센서 장착 방향
    unit_axis: "z"

    # =============================================================================
    # RANSAC 알고리즘 파라미터
    # =============================================================================
    
    # RANSAC 최대 반복 횟수
    # 값 증가 → 더 정확한 평면 추정, 느린 처리
    # 값 감소 → 빠른 처리, 부정확할 수 있음
    # 권장: 노이즈 적은 환경 100-200, 노이즈 많은 환경 300-500
    max_iterations: 200
    
    # 최소 시도 횟수 (코드에서 min_inliers로 사용됨)
    # RANSAC에서 유효한 모델로 인정하기 위한 최소 inlier 개수
    # 값 증가 → 더 엄격한 평면 검증, 안정성 향상
    # 값 감소 → 더 관대한 평면 수용, 스파스한 데이터 처리
    # 권장: 전체 포인트의 5-15%
    min_trial: 100
    
    # 처리를 위한 최소 포인트 개수
    # 이 개수 미만이면 RANSAC 수행하지 않음
    # 값 증가 → 더 안정적인 처리, 스파스한 데이터 무시
    # 값 감소 → 적은 데이터로도 처리, 불안정할 수 있음
    min_points: 50

    # =============================================================================
    # 지면 검출 임계값 파라미터
    # =============================================================================
    
    # RANSAC outlier 임계값 [m]
    # 추정된 평면에서 이 거리 이내의 점을 inlier로 간주
    # 값 증가 → 더 많은 포인트를 지면으로 분류 (관대한 검출)
    # 값 감소 → 더 정확한 평면 추정 (엄격한 검출)
    # 권장: 실내 0.05-0.1m, 실외 0.1-0.2m, 거친 지형 0.2-0.3m
    outlier_threshold: 0.15
    
    # 평면 경사 각도 임계값 [degree]
    # 추정된 평면이 수직축과 이루는 최대 허용 각도
    # 값 증가 → 더 가파른 경사까지 지면으로 인식 (언덕길)
    # 값 감소 → 더 평평한 면만 지면으로 인식 (평지)
    # 권장: 평지 10-15도, 언덕길 20-30도, 실내 5-10도
    plane_slope_threshold: 15.0
    
    # 최종 지면/비지면 분류 높이 임계값 [m]
    # 추정된 지면 평면에서 이 높이 이상의 포인트를 장애물로 분류
    # 값 증가 → 더 높은 물체만 장애물로 인식 (작은 물체 무시)
    # 값 감소 → 작은 돌출부도 장애물로 인식 (민감한 검출)
    # 권장: 실내 0.1-0.15m, 실외 0.15-0.25m, 거친 지형 0.25-0.4m
    height_threshold: 0.20

    # =============================================================================
    # 전처리 복셀 필터 파라미터
    # =============================================================================
    
    # 복셀 그리드 X축 크기 [m]
    # RANSAC 전 다운샘플링을 위한 복셀 크기
    # 값 증가 → 더 적은 포인트, 빠른 처리, 정확도 감소
    # 값 감소 → 더 많은 포인트, 느린 처리, 정확도 향상
    # 권장: 일반적으로 0.05-0.2m
    voxel_size_x: 0.10
    
    # 복셀 그리드 Y축 크기 [m]
    # X축과 동일한 원리, 보통 x와 같은 값 사용
    voxel_size_y: 0.10
    
    # 복셀 그리드 Z축 크기 [m]
    # 높이 방향 복셀 크기, 지면 검출 정확도에 직접 영향
    # 값 증가 → 높이 변화에 덜 민감, 빠른 처리
    # 값 감소 → 높이 변화에 민감, 정확한 지면 검출
    # 권장: x, y보다 작게 설정 (0.05-0.15m)
    voxel_size_z: 0.10

    # =============================================================================
    # 디버그 및 모니터링 옵션
    # =============================================================================
    
    # 디버그 정보 발행 여부
    # true: 추정된 지면 평면과 지면 포인트를 시각화
    # false: 디버그 정보 비활성화로 성능 향상
    debug: false
    
    # 상세 처리 시간 정보 발행 여부
    # true: 각 단계별 처리 시간을 /debug/processing_time_detail_ms 토픽으로 발행
    # false: 처리 시간 정보 비활성화로 성능 향상
    publish_processing_time_detail: false

# =============================================================================
# 환경별 튜닝 가이드
# =============================================================================
#
# 1. 실내 환경 (평평한 바닥):
#    - outlier_threshold: 0.05
#    - plane_slope_threshold: 5.0
#    - height_threshold: 0.10
#    - voxel_size_x/y/z: 0.05
#    - max_iterations: 100
#
# 2. 실외 포장도로:
#    - outlier_threshold: 0.15
#    - plane_slope_threshold: 10.0
#    - height_threshold: 0.20
#    - voxel_size_x/y/z: 0.10
#    - max_iterations: 200
#
# 3. 실외 비포장도로/거친 지형:
#    - outlier_threshold: 0.25
#    - plane_slope_threshold: 20.0
#    - height_threshold: 0.30
#    - voxel_size_x/y/z: 0.15
#    - max_iterations: 300
#
# 4. 언덕길/경사로:
#    - outlier_threshold: 0.20
#    - plane_slope_threshold: 30.0
#    - height_threshold: 0.25
#    - max_iterations: 250
#
# 5. 고속 처리 우선 (성능 최적화):
#    - outlier_threshold: 0.20
#    - max_iterations: 50
#    - min_trial: 50
#    - voxel_size_x/y/z: 0.20
#    - debug: false
#    - publish_processing_time_detail: false
#
# 6. 정확도 우선 (품질 최적화):
#    - outlier_threshold: 0.10
#    - max_iterations: 500
#    - min_trial: 200
#    - voxel_size_x/y/z: 0.05
#    - height_threshold: 0.15
#
# 7. 스파스한 포인트클라우드 (VLP-16 등):
#    - min_points: 30
#    - min_trial: 50
#    - outlier_threshold: 0.20
#    - voxel_size_x/y/z: 0.15
#
# 8. 덴스한 포인트클라우드 (Velodyne HDL-64E 등):
#    - min_points: 100
#    - min_trial: 200
#    - outlier_threshold: 0.10
#    - voxel_size_x/y/z: 0.05

# =============================================================================
# 성능 vs 정확도 트레이드오프 가이드
# =============================================================================
#
# 처리 속도 향상을 원할 때:
# 1. max_iterations 감소 (200 → 100)
# 2. voxel_size 증가 (0.1 → 0.2)
# 3. debug 비활성화
# 4. publish_processing_time_detail 비활성화
#
# 정확도 향상을 원할 때:
# 1. outlier_threshold 감소 (0.15 → 0.10)
# 2. voxel_size 감소 (0.1 → 0.05)
# 3. max_iterations 증가 (200 → 300)
# 4. height_threshold 조정
#
# 특정 환경 문제 해결:
# - 지면을 놓치는 경우: outlier_threshold 증가, plane_slope_threshold 증가
# - 장애물을 지면으로 오인: height_threshold 감소, plane_slope_threshold 감소
# - 노이즈가 많은 경우: min_trial 증가, max_iterations 증가
# - 처리가 너무 느린 경우: voxel_size 증가, max_iterations 감소
