/**:
  ros__parameters:
    min_x: -3.0
    max_x: 3.0
    min_y: -3.0
    max_y: 3.0
    use_vehicle_footprint: false
    general_max_slope: 10.0
    local_max_slope: 7.0
    initial_max_slope: 3.0
    radial_divider_angle: 0.5
    min_height_threshold: 0.03
    concentric_divider_distance: 0.15
    reclass_distance_threshold: 0.15

    # debug parameters
    publish_processing_time_detail: false
