/**:
  ros__parameters:
    elevation_grid_mode: false
    use_virtual_ground_point: false

        # 실내 평지, 바닥 링 제거 강화를 위한 파라미터
    global_slope_max_angle_deg: 10.0
    local_slope_max_angle_deg: 13.0	
    split_points_distance_tolerance: 0.40   # 레이 간격 넓게 허용
    split_height_distance: 0.50             # 지면 seed 연결 허용 높이
    non_ground_height_threshold: 0.15       # 지면 오차 허용

    radial_divider_angle_deg: 0.5

        # 기타
    grid_size_m: 0.20
    grid_mode_switch_radius: 20.0
    gnd_grid_buffer_size: 2
    detection_range_z_max: 5.0
    low_priority_region_x: -20.0
    center_pcl_shift: 0.0
    use_recheck_ground_cluster: true
    use_lowest_point: true

    publish_processing_time_detail: false
